-- Migration 035: skill_files table + skills-files storage bucket
-- Phase 7 / Plan 07-02 — foundation for SFILE-* (Phase 8+)
-- Depends on: 034_skills_table_and_seed.sql (skills table must exist)
-- All table DDL uses CREATE IF NOT EXISTS; bucket INSERT uses ON CONFLICT DO NOTHING.
-- Storage RLS policies use CREATE POLICY (applied once by migration runner).

-- ============================================================
-- 1. TABLE: public.skill_files
-- ============================================================
-- Path scheme: {owner_id}/{skill_id}/{filename}
--   owner_id = user_id (private skills)
--   owner_id = created_by (shared/global skills)
--   owner_id = '_system' (seed-time skill-creator files)
--
-- Size cap: 10 MB per file (D-P7-08). Duplicated in skill_zip_service.
-- CHECK constraints (D-P7-09):
--   (1) storage_path_shape: three-segment path matching UUID in segment 2
--   (2) storage_path_skill_match: segment 2 MUST equal skill_id column value
--       → blocks cycle-1 HIGH #2: row pointing at another skill's blob

CREATE TABLE IF NOT EXISTS public.skill_files (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  skill_id      UUID NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
  filename      TEXT NOT NULL,
  size_bytes    BIGINT NOT NULL CHECK (size_bytes >= 0 AND size_bytes <= 10485760),  -- 10 MB cap (D-P7-08)
  mime_type     TEXT,
  storage_path  TEXT NOT NULL UNIQUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  -- Cycle-1 review HIGH #2: bind storage_path to (owner, skill_id).
  -- Path must be {segment1}/{uuid-segment2}/{filename}; segment2 must match skill_id.
  CONSTRAINT skill_files_storage_path_shape CHECK (
    storage_path ~ '^[a-zA-Z0-9_-]+/[0-9a-fA-F-]{36}/[^/]+$'
  ),
  CONSTRAINT skill_files_storage_path_skill_match CHECK (
    split_part(storage_path, '/', 2) = skill_id::text
  )
);

-- ============================================================
-- 2. INDEX
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_skill_files_skill_id
  ON public.skill_files(skill_id);

-- ============================================================
-- 3. ROW-LEVEL SECURITY — skill_files table
-- ============================================================

ALTER TABLE public.skill_files ENABLE ROW LEVEL SECURITY;

-- SELECT: visible if the parent skill is visible to the caller
--   (own private skill OR global skill with user_id IS NULL)
CREATE POLICY "skill_files_select"
  ON public.skill_files
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.skills s
      WHERE s.id = skill_files.skill_id
        AND (s.user_id = auth.uid() OR s.user_id IS NULL)
    )
  );

-- INSERT: parent skill must be private and owned by caller;
--         created_by must be caller; storage_path first segment must be caller UID.
--         This is the table-level enforcement of cycle-1 HIGH #2 mitigation.
CREATE POLICY "skill_files_insert"
  ON public.skill_files
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.skills s
      WHERE s.id = skill_files.skill_id
        AND s.user_id = auth.uid()
    )
    AND created_by = auth.uid()
    AND split_part(storage_path, '/', 1) = auth.uid()::text
  );

-- DELETE: own files on private skills only (original creator only)
-- No UPDATE policy — files are immutable; replace = delete + insert.
CREATE POLICY "skill_files_delete"
  ON public.skill_files
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.skills s
      WHERE s.id = skill_files.skill_id
        AND s.user_id = auth.uid()
    )
    AND created_by = auth.uid()
  );

-- ============================================================
-- 4. STORAGE BUCKET: skills-files (D-P7-07)
-- ============================================================
-- Private bucket (public = false). Objects are accessed only via
-- signed URLs generated by the API. No public CDN exposure.

INSERT INTO storage.buckets (id, name, public)
VALUES ('skills-files', 'skills-files', false)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 5. STORAGE RLS — storage.objects policies for skills-files
-- ============================================================
-- Cycle-1 HIGH #1 fix: SELECT policy joins to skill_files by EXACT storage_path,
-- not first-segment matching, so unrelated objects under same owner folder are not
-- leaked to users with global skills.
--
-- Cycle-2 NEW-H1 fix: INSERT policy requires parent skill to be PRIVATE (user_id = auth.uid())
-- so creators cannot mutate globally-shared skill blobs via Storage directly.

-- SELECT: readable iff a skill_files row exists for this exact path AND parent skill is visible
CREATE POLICY "skills-files SELECT"
  ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'skills-files'
    AND EXISTS (
      SELECT 1
      FROM public.skill_files sf
      JOIN public.skills s ON s.id = sf.skill_id
      WHERE sf.storage_path = storage.objects.name
        AND (s.user_id = auth.uid() OR s.user_id IS NULL)
    )
  );

-- INSERT: caller's UID matches first segment (owner folder);
--         second segment must look like a UUID (regex guard);
--         a PRIVATE parent skill exists with that id, created by caller.
--         Cycle-2 NEW-H1: parent must be private (s.user_id = auth.uid()).
CREATE POLICY "skills-files INSERT"
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'skills-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
    AND (storage.foldername(name))[2] ~ '^[0-9a-fA-F-]{36}$'
    AND EXISTS (
      SELECT 1
      FROM public.skills s
      WHERE s.id::text = (storage.foldername(name))[2]
        AND s.created_by = auth.uid()
        AND s.user_id    = auth.uid()   -- parent must be PRIVATE; creator must unshare to edit
    )
  );

-- DELETE: same predicate as INSERT — must own the parent private skill
CREATE POLICY "skills-files DELETE"
  ON storage.objects
  FOR DELETE
  USING (
    bucket_id = 'skills-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
    AND (storage.foldername(name))[2] ~ '^[0-9a-fA-F-]{36}$'
    AND EXISTS (
      SELECT 1
      FROM public.skills s
      WHERE s.id::text = (storage.foldername(name))[2]
        AND s.created_by = auth.uid()
        AND s.user_id    = auth.uid()   -- parent must be PRIVATE
    )
  );
